### PR TITLE
fix bug: unpad plaintext for sm4_cbc decrypt

### LINKED ISSUE #311: Bug: padding is returned as part of plaintext in the SM4_CBC decryption
## Description

Padding of data is also returned as part of data in SM4_CBC decryption, which causes the inconsistence between plaintext and result of decryption.

## Reproduction

The following script is a minimal reproduction. Save it to `bug.py` in the `ehsm/test` folder and run.

```python
from cli import createkey, enroll, decrypt, encrypt, enroll
import base64
import _utils_

# !!! CHANGE ME IF NEEDED
BASE_URL = 'https://127.0.0.1:9002/ehsm?Action='

appid, apikey = '', ''
appid, apikey = enroll.enroll(BASE_URL)
_utils_.init_appid_apikey(appid, apikey)

keyid = createkey.createkey(BASE_URL, "EH_SM4_CBC", "EH_INTERNAL_KEY", "EH_KEYUSAGE_ENCRYPT_DECRYPT")
text = "symmetricKey"

aad = str(base64.b64encode("test".encode("utf-8")),'utf-8')
data = str(base64.b64encode(text.encode("utf-8")),'utf-8')

# encrypt
ciphertext = encrypt.encrypt(BASE_URL, keyid, data, aad)

# test Decrypt(ciphertext)
plaintext = decrypt.decrypt(BASE_URL, keyid, ciphertext, aad)

try:
    assert plaintext == text
    print("\033[32m", "PASS", "\033[0m", sep='')
except AssertionError:
    print("\033[31m", "FAIL", "\033[0m", sep='')
    print("decrypted:")
    print(plaintext.encode())
    print("origin:")
    print(text.encode())
```

The result should be:

```
<output of the cli>
FAIL
decrypted:
b'symmetricKey\x04\x04\x04\x04'
origin:
b'symmetricKey'
```

## Note

Note that the padding only occurs when `len(text) % 8 != 0`.

### PR DESCRIPTION
**Pull request by whh39**
Fixes #311

### CODE REVIEW

File: core/Enclave/self_test/sm4_test.cpp [hunk 1]
```diff
@@ -84,7 +84,7 @@ static bool sm4_cbc_decryption(map<string, string> test_vector)
     GET_PARAMETER(iv);
     GET_PARAMETER(ciphertext);
 
-    uint8_t _plaintext[VECTOR_LENGTH("plaintext")] = {0};
+    ehsm_data_t *_plaintext = (ehsm_data_t*)malloc(APPEND_SIZE_TO_DATA_T(VECTOR_LENGTH("plaintext")));
     (void)sm4_cbc_decrypt(&*key,
```
Comment (yang8621) [inline core/Enclave/self_test/sm4_test.cpp:88]: not free?

File: core/Enclave/openssl_operation.cpp [hunk 2]
```diff
@@ -342,7 +352,7 @@ sgx_status_t sm4_cbc_decrypt(uint8_t *key,
     int temp_len = 0;
     EVP_CIPHER_CTX *pctx = NULL;
 
-    int pad = (ciphertext_len % 16 == 0) ? 0 : 1;
+    int pad = (ciphertext_len % 16 == 0) ? SM4_NO_PAD : SM4_PAD;
```
Comment (truc0) [inline core/Enclave/openssl_operation.cpp:355]: It seems that the ciphertext_len will always satisfy `ciphertext_len % 16 == 0` because:

- If `len(text_before_encryption) % 16 == 0`, the `ciphertext_len % 16 == 0`
- If `len(text_before_encryption) % 16 != 0`, the encryption will add padding to ensure `len(text_before_encryption) % 16 == 0`

File: core/Enclave/openssl_operation.cpp [hunk 3]
```diff
@@ -58,6 +58,16 @@
 #define SM4_NO_PAD 0
 #define SM4_PAD 1
 
+static void pkcs7_unpadding(ehsm_data_t *plaintext, int length)
+{
+    int pad = plaintext->data[length - 1];
```
Comment (truc0) [inline core/Enclave/openssl_operation.cpp:63]: If the plaintext is ended with a newline character (`\n`, `0xA` in ASCII) and its length is the multiple of 16, this function will remove the last ten characters of the ciphertext.

**Comment by truc0** [comment]
The following test case does not pass. Copy it to `ehsm/test/report.py` for correct importing helper modules.

```python
# from cli import createkey, enroll, decrypt, encrypt, generate_datakey, generate_datakey_withoutplaint, generate_quote, getversion, sign, verify, verify_quote, enroll, uploadQuotePolicy, getQuotePolicy, getPubkey
from cli import createkey, enroll, decrypt, encrypt, enroll
import base64
import _utils_

# CHANGE ME IF NEEDED
BASE_URL = 'https://127.0.0.1:9002/ehsm?Action='

appid, apikey = enroll.enroll(BASE_URL)
_utils_.init_appid_apikey(appid, apikey)

keyid = createkey.createkey(BASE_URL, "EH_SM4_CBC", "EH_INTERNAL_KEY", "EH_KEYUSAGE_ENCRYPT_DECRYPT")

# 16 chars with newline(0xA) ended
text = "symmetricKeyaka\n"
# text = "symmetricKey"

aad = str(base64.b64encode("test".encode("utf-8")),'utf-8')
data = str(base64.b64encode(text.encode("utf-8")),'utf-8')

# encrypt
ciphertext = encrypt.encrypt(BASE_URL, keyid, data, aad)

# test Decrypt(ciphertext)
plaintext = decrypt.decrypt(BASE_URL, keyid, ciphertext, aad)

try:
    assert plaintext == text
    print("\033[32m", "PASS", "\033[0m", sep='')
except AssertionError:
    print("\033[31m", "FAIL", "\033[0m", sep='')
    print("decrypted:")
    print(plaintext.encode())
    print("origin:")
    print(text.encode())
```

**Comment by whh39** [comment]
#312

File: ehsm_kms_service/payload_checker.js [hunk 4]
```diff
@@ -49,7 +49,7 @@ const keyid = {
 }
 const aad = {
   type: PARAM_DATA_TYPE.BASE64,
-  maxLength: MAX_LENGTH,
+  maxLength: MAX_LENGTH * 4 / 3,  // This is the length after base64 encoding.
```
Comment (yang8621) [inline ehsm_kms_service/payload_checker.js:52]: any relation to the fix? if not, please create a new patch for it.

Comment (whh39) [reply ehsm_kms_service/payload_checker.js]: already clear this

File: core/Enclave/openssl_operation.cpp (hunk 2 above)
Comment (whh39) [reply core/Enclave/openssl_operation.cpp]: New code is upload and I try to use EVP api only to solve the issue
EVP_DecryptFinal_ex should unpad auto and it seems work well in unittest test

**Review by yang8621 — APPROVED** [review]
